### ISSUE TITLE
the nats repicas config is not exposed on values.yaml

### ISSUE THREAD

**Issue by LinPr** [openobserve/openobserve-helm-chart#125]
currently the nats config in values.yaml is as follows 

``` yaml
nats:
  enabled: true # if true then nats will be deployed as part of openobserve
  externalUrl: "my_custom_host.com:4222" # if enabled is false then this is required
  config:
    cluster:
      enabled: true
    routeURLs:
      user: ""
      password: ""
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        pvc:
          enabled: true
          size: 20Gi
          storageClassName: "local-openobserve"
    promExporter:
      enabled: true
      podMonitor:
        enabled: true
    natsBox:
      container:
        image:
          repository: natsio/nats-box
          tag: 0.14.5-nonroot

```

but other components like etcd , ingester, querier  all have ablity to set replicats in values.yaml , for example  etcd 

``` yaml 
etcd:
  enabled: false # if true then etcd will be deployed as part of openobserve
  externalUrl: "my_custom_host.com:2379" # if enabled is false then this is required
  replicaCount: 3 # if enabled is true then this is required. should be odd number
  clusterDomain: "cluster.local"
  image:
    registry: docker.io
    repository: bitnami/etcd
.....
```

so I recommend to expose the nats replicas config in values.yaml ,  and I will make a PR for this, hope this proposal could be accepted
