### ISSUE TITLE
Issue when using extraEnv to override config and auth

### ISSUE THREAD

**Issue by alimorseltelostouch** [openobserve/openobserve-helm-chart#133]
i tried to use a k8s secret to override the existing config an auth, but it seems like it's still using the default ones.
so i have added for example this secret as an extraEnv

```
extraEnv:
  - name: ZO_ROOT_USER_EMAIL
    valueFrom:
      secretKeyRef:
        name: oo-secret
        key: ZO_ROOT_USER_EMAIL
  - name: ZO_ROOT_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: oo-secret
        key: ZO_ROOT_USER_PASSWORD
```

the oo-secret created manually.
am i doing something wrong ?
