### ISSUE TITLE
router needed/replaced?

### ISSUE THREAD

**Issue by genofire** [openobserve/openobserve-helm-chart#22]
Why is the router needed?
Could you replace it by an better designed Ingress or if it is not possible with an Ingress, then with an Gateway API ?

**Comment by prabhatsharma** [comment]
Router can indeed be replaced by a configuration of ingress. However OpenObserve can be run in multiple environments. With multiple ingress (nginx, haproxy, ...) it will be difficult to support a large number of users with different kind of environments. Providing a router basically solves that problem.

**Comment by genofire** [comment]
We are talking about this helmchart and the [Ingress]() or [GatewayAPI](https://gateway-api.sigs.k8s.io/).
So every Ingress-Controller support it, like traefik, nginx and haproxy.


if you talk about a deployment on a VM, then it will make a sense.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openoberve
spec:
  rules:
    - host: "openobserve.example.org"
      http:
        paths:
          - path: "/summary"
            pathType: Prefix
            backend:
              service:
                name: "openobserve-querier"
                port:
                  name: http
          - path: "/schema"
            pathType: Prefix
            backend:
              service:
                name: "openobserve-querier"
                port:
                  name: http
          # ...
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "openobserve-ingester"
                port:
                  name: http
```
