### ISSUE TITLE
Getting aws s3 region not specified

### ISSUE THREAD

**Issue by kssanthosh** [openobserve/openobserve-helm-chart#4]
Getting below error

`[2023-04-10T16:20:30Z INFO  aws_config::meta::region] load_region; provider=EnvironmentVariableRegionProvider { env: Env(Real) }
[2023-04-10T16:20:30Z INFO  aws_config::meta::region] load_region; provider=ProfileFileRegionProvider { provider_config: ProviderConfig { env: Env(Real), fs: Fs(Real), sleep: Some(TokioSleep), region: None } }
[2023-04-10T16:20:30Z INFO  aws_config::meta::region] load_region; provider=ImdsRegionProvider { client: LazyClient { client: OnceCell { value: None }, builder: Builder { max_attempts: None, endpoint: None, mode_override: None, token_ttl: None, connect_timeout: None, read_timeout: None, config: Some(ProviderConfig { env: Env(Real), fs: Fs(Real), sleep: Some(TokioSleep), region: None }) } }, env: Env(Real) }
[2023-04-10T16:20:31Z INFO  zincobserve::infra::cluster] [TRACE] cluster->node: join Node { id: 2, uuid: "6db0ab30-d083-4888-ac44-cb10f7e7a448", name: "zo1-zincobserve-alertmanager-5c595669-sbcdg", http_addr: "http://100.102.20.31:5080", grpc_addr: "http://100.102.20.31:5081", role: [AlertManager], cpu_num: 4, status: Prepare }
[2023-04-10T16:20:31Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: timeout: HTTP read timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: HttpTimeoutError { kind: "HTTP read", duration: 1s } } }) }))
[2023-04-10T16:20:31Z INFO  aws_config::meta::region] load_region; provider=EnvironmentVariableRegionProvider { env: Env(Real) }
[2023-04-10T16:20:31Z INFO  aws_config::meta::region] load_region; provider=ProfileFileRegionProvider { provider_config: ProviderConfig { env: Env(Real), fs: Fs(Real), sleep: Some(TokioSleep), region: None } }
[2023-04-10T16:20:31Z INFO  aws_config::meta::region] load_region; provider=ImdsRegionProvider { client: LazyClient { client: OnceCell { value: None }, builder: Builder { max_attempts: None, endpoint: None, mode_override: None, token_ttl: None, connect_timeout: None, read_timeout: None, config: Some(ProviderConfig { env: Env(Real), fs: Fs(Real), sleep: Some(TokioSleep), region: None }) } }, env: Env(Real) }
[2023-04-10T16:20:32Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: timeout: HTTP read timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: HttpTimeoutError { kind: "HTTP read", duration: 1s } } }) }))
[2023-04-10T16:20:32Z ERROR zincobserve::infra::storage::s3] s3 list objects file_list/ error: ConstructionFailure(ConstructionFailure { source: ResolveEndpointError { message: "A region must be set when sending requests to S3.", source: None } })
thread 'tokio-runtime-worker' panicked at 'job init failed: s3 list objects error`

Even though i have specified the region in the values. Please find the helm values i have used.

```yaml

image:
  repository: public.ecr.aws/zinclabs/zincobserve
  pullPolicy: IfNotPresent
  tag: "v0.3.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000
  runAsUser: 10000
  runAsGroup: 3000
  runAsNonRoot: true

replicaCount:
  ingester: 1
  querier: 1
  router: 1
  alertmanager: 1
  compactor: 1

ingester:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    annotations: {}
    volumePermissions:
      enabled: false

auth:
  ZO_ROOT_USER_EMAIL: "root@zincobserver"
  ZO_ROOT_USER_PASSWORD: "test#123"
  ZO_S3_ACCESS_KEY: "accesskey"
  ZO_S3_SECRET_KEY: "secretid" 

config:
  ZO_LOCAL_MODE: "false"
  ZO_HTTP_PORT: "5080"
  ZO_GRPC_PORT: "5081"
  ZO_GRPC_TIMEOUT: "600"
  ZO_GRPC_ORG_HEADER_KEY: "zinc-org-id"
  ZO_ROUTE_TIMEOUT: "600"
  ZO_LOCAL_MODE_STORAGE: "s3"
  ZO_NODE_ROLE: "all"
  ZO_INSTANCE_NAME: ""
  ZO_DATA_DIR: "./data/"
  ZO_DATA_WAL_DIR: ""
  ZO_DATA_STREAM_DIR: ""
  ZO_WAL_MEMORY_MODE_ENABLED: "false"
  ZO_FILE_EXT_JSON: ".json"
  ZO_FILE_EXT_PARQUET: ".parquet"
  ZO_PARQUET_COMPRESSION: "zstd"
  ZO_TIME_STAMP_COL: "_timestamp"
  ZO_WIDENING_SCHEMA_EVOLUTION: "false"
  ZO_FEATURE_PER_THREAD_LOCK: "false"
  ZO_FEATURE_FULLTEXT_ON_ALL_FIELDS: "false"
  ZO_UI_ENABLED: "true"
  ZO_METRICS_DEDUP_ENABLED: "true"
  ZO_TRACING_ENABLED: "false"
  OTEL_OTLP_HTTP_ENDPOINT: "http://127.0.0.1:5080/api/nexus/traces"
  ZO_TRACING_HEADER_KEY: "Authorization"
  ZO_TRACING_HEADER_VALUE: "Basic YWRtaW46Q29tcGxleHBhc3MjMTIz"
  ZO_TELEMETRY: "true"
  ZO_TELEMETRY_URL: "https://e1.zinclabs.dev"
  ZO_JSON_LIMIT: "209715200"
  ZO_PAYLOAD_LIMIT: "209715200"
  ZO_MAX_FILE_SIZE_ON_DISK: "10"
  ZO_MAX_FILE_RETENTION_TIME: "600"
  ZO_FILE_PUSH_INTERVAL: "10"
  ZO_FILE_MOVE_THREAD_NUM: "0"
  ZO_QUERY_THREAD_NUM: "0"
  ZO_TS_ALLOWED_UPTO: "5"
  ZO_METRICS_LEADER_PUSH_INTERVAL: "15"
  ZO_METRICS_LEADER_ELECTION_INTERVAL: "30"
  ZO_HEARTBEAT_INTERVAL: "30"
  ZO_COMPACT_ENABLED: "true"
  ZO_COMPACT_INTERVAL: "60"
  ZO_COMPACT_MAX_FILE_SIZE: "256"
  ZO_MEMORY_CACHE_ENABLED: "true"
  ZO_MEMORY_CACHE_CACHE_LATEST_FILES: "false"
  ZO_MEMORY_CACHE_MAX_SIZE: "0"
  ZO_MEMORY_CACHE_RELEASE_SIZE: "0"
  RUST_LOG: debug
  ZO_COLS_PER_RECORD_LIMIT: "200"
  ZO_ETCD_PREFIX: "/zinc/observe/"
  ZO_ETCD_CONNECT_TIMEOUT: "2"
  ZO_ETCD_COMMAND_TIMEOUT: "5"
  ZO_ETCD_LOCK_WAIT_TIMEOUT: "600"
  ZO_ETCD_USER: ""
  ZO_ETCD_PASSWORD: ""
  ZO_ETCD_CLIENT_CERT_AUTH: "false"
  ZO_ETCD_TRUSTED_CA_FILE: ""
  ZO_ETCD_CERT_FILE: ""
  ZO_ETCD_KEY_FILE: ""
  ZO_ETCD_DOMAIN_NAME: ""
  ZO_ETCD_LOAD_PAGE_SIZE: "10000"
  ZO_SLED_DATA_DIR: ""
  ZO_SLED_PREFIX: "/zinc/observe/"
  ZO_S3_SERVER_URL: "" 
  ZO_S3_REGION_NAME: "region"
  ZO_S3_BUCKET_NAME: "bucketname"
  ZO_DATA_LIFECYCLE: "0"
  ZO_S3_PROVIDER: "aws"
  RUST_BACKTRACE: "1"

service:
  type: ClusterIP
  port: 5080

certIssuer:
  enabled: false

ingress:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1028Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

etcd:
  enabled: true
  externalUrl: "my_custom_host.com:2379"
  replicaCount: 3
  image:
    registry: docker.io
    repository: bitnami/etcd
    tag: 3.5.7-debian-11-r10
    digest: ""
  auth:
    rbac:
      create: false
      allowNoneAuthentication: true
      rootPassword: ""
  logLevel: "info"
  extraEnvVars:
    - name: ETCD_QUOTA_BACKEND_BYTES
      value: "17179869184"
  persistence:
    size: 20Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    annotations: {}

minio:
  enabled: false
  region: "us-east-1"
  rootUser: rootuser
  rootPassword: rootpass123
  drivesPerNode: 1
  replicas: 4
  mode: distributed
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2023-02-10T18-48-39Z
    pullPolicy: IfNotPresent
  mcImage:
    repository: quay.io/minio/mc
    tag: RELEASE.2023-01-28T20-29-38Z
    pullPolicy: IfNotPresent
  buckets:
    - name: mysuperduperbucket
      policy: none
      purge: false
  resources:
    requests:
      memory: 256Mi
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    annotations: {}

```
