### ISSUE TITLE
Error during Helm installation

### ISSUE THREAD

**Issue by vb3328998** [openobserve/openobserve-helm-chart#58]
### Content:
I encountered an error while installing a Helm chart. Here is the command I used and the error messages I received:
```shell
helm install -n itnio-openobserve -f pre-values.yaml openobserve --set fullnameOverride=openobserve .
```
### Error Messages:
coalesce.go:175: warning: skipped value for etcd.tolerations: Not a table.
coalesce.go:175: warning: skipped value for etcd.replicaCount: Not a table.
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "openobserve-postgres" namespace: "itnio-openobserve" from "": no matches for kind "Cluster" in version "postgresql.cnpg.io/v1"
ensure CRDs are installed first
make: *** [install] Error 1

### CHart Version:
```yaml
apiVersion: v2
appVersion: v0.10.5
dependencies:
- condition: etcd.enabled
  name: etcd
  repository: https://charts.bitnami.com/bitnami
  version: 8.11.4
- condition: nats.enabled
  name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 1.1.11
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io
  version: 5.0.7
description: Logs, Metrics and Traces, Dashboards, RUM, Error tracking, Session replay
  etc. Elasticsearch API compatibility.
maintainers:
- email: hello@openobserve.ai
  name: OpenObserve
  url: https://openobserve.ai
name: openobserve
type: application
version: 0.10.15
```
### kubernetes version:
eks 1.29
### Question:
 How can I fix this issue?
